general:
steps:
  mtaBuild:
    buildTarget: 'CF'
  cloudFoundryDeploy:
    deployTool: 'mtaDeployPlugin'
    deployType: 'standard'
    cloudFoundry:
      apiEndpoint: 'https://api.cf.us10-001.hana.ondemand.com/'
      org: 'ee8498eatrial'
      space: 'dev'
      credentialsId: 'CF_CREDENTIAL_EPAM'
