general:
steps:
  mtaBuild:
    buildTarget: 'CF'
      cloudFoundryDeploy:
    deployTool: 'mtaDeployPlugin'
    deployType: 'standard'
    cloudFoundry:
      org: '88545584-96e5-4360-a58b-705a9a8cc52e'
      space: 'dev'
      credentialsId: 'CF_CREDENTIALSID'

